default: &default
 adapter: postgresql
 encoding: unicode
 min_messages: WARNING
 pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
 host: <%= ENV.fetch("POSTGRES_HOSTNAME", "localhost") %>
 username: <%= ENV.fetch("POSTGRES_USERNAME", 'postgres') %>
 password: <%= ENV.fetch("POSTGRES_PASSWORD", 'root') %>

development:
 <<: *default
 database: <%= ENV.fetch("POSTGRES_DATABASE", "youngsters") %>

test:
 <<: *default
 database: <%= ENV.fetch("POSTGRES_DATABASE", "youngsterstest") %>

production:
 <<: *default
 database: <%= ENV.fetch("POSTGRES_DATABASE", "youngsters") %>
